const js = require('@eslint/js');
const globals = require('globals');

const sharedRules = {
    ...js.configs.recommended.rules,
    'no-unused-vars': ['warn', { args: 'none', caughtErrors: 'none' }],
    'no-undef': 'warn',
    'no-shadow': 'warn',
    eqeqeq: 'warn',
    'no-empty': ['warn', { allowEmptyCatch: false }],
    'prefer-const': 'warn',
    'max-lines': ['warn', { max: 400, skipBlankLines: true, skipComments: true }],
    'max-lines-per-function': ['warn', { max: 80, skipBlankLines: true, skipComments: true }],
    complexity: ['warn', 15],
};

const frontendGlobals = {
    ...globals.browser,
    lucide: 'readonly',
    gsap: 'readonly',
    Motion: 'readonly',
    MobileConfig: 'readonly',
    MobileRuntime: 'readonly',
    AedosThinking: 'readonly',
    BrowserLogger: 'readonly',
    currentLang: 'readonly',
    outlineEditorState: 'readonly',
    currentSlide: 'readonly',
    __t: 'readonly',
    __applyTranslations: 'readonly',
    initEditorUI: 'readonly',
    initMinimap: 'readonly',
    initTools: 'readonly',
    nextSlide: 'readonly',
    prevSlide: 'readonly',
    getCurrentSlide: 'readonly',
    getTotalSlides: 'readonly',
    scrollToSlide: 'readonly',
    editorArrowMove: 'readonly',
    editorDeleteSelection: 'readonly',
    editorDeselect: 'readonly',
    editorDuplicateSelection: 'readonly',
    editorGetSelection: 'readonly',
    editorIsDragging: 'readonly',
    editorRedo: 'readonly',
    editorSaveState: 'readonly',
    editorSelect: 'readonly',
    editorUndo: 'readonly',
    editorUpdateSelection: 'readonly',
    freezeAllSlides: 'readonly',
    setLocked: 'readonly',
    toBack: 'readonly',
    toFront: 'readonly',
    regenerateDotsCount: 'readonly',
    fillInput: 'readonly',
    navigateToChat: 'readonly',
    navigateToEditor: 'readonly',
    navigateToHome: 'readonly',
    parsePartialSkeleton: 'readonly',
    prepareOutlineStreaming: 'readonly',
    proceedWithCurrentOutline: 'readonly',
    renderStreamingOutline: 'readonly',
    showOutlineEditorLoading: 'readonly',
    startFinalGeneration: 'readonly',
    stopOutlineGeneration: 'readonly',
    validateGenerateButton: 'readonly',
    finalizeStreamingOutline: 'readonly',
    addBlankPoint: 'readonly',
    deleteSlide: 'readonly',
    moveSlideDown: 'readonly',
    moveSlideUp: 'readonly',
    renderOutlineSuggestedChips: 'readonly',
    initOutlineEditor: 'readonly',
    resumeOutlineEditor: 'readonly',
    _keydownHandler: 'readonly',
    _minimapInterval: 'readonly',
    _editorInitialized: 'readonly',
    _addImageHandler: 'readonly',
    _mobile_zoom: 'readonly',
    _pan: 'readonly',
    _baseScale: 'readonly',
    _iframeScale: 'readonly',
    toggleMobileDrawer: 'readonly',
};

module.exports = [
    {
        ignores: [
            '**/node_modules/**',
            '**/tmp/**',
            '**/examples/**',
            '**/tests/fixtures/**',
            '**/tests/baseline/**',
            '**/puppeteer-cache/**',
            'eslint.config.js',
        ],
    },
    {
        files: ['src/backend/**/*.js', 'scripts/**/*.js', 'tests/**/*.js'],
        languageOptions: { ecmaVersion: 'latest', sourceType: 'commonjs', globals: globals.node },
        rules: sharedRules,
    },
    {
        files: ['src/frontend/**/*.js'],
        languageOptions: { ecmaVersion: 'latest', sourceType: 'script', globals: frontendGlobals },
        rules: sharedRules,
    },
    {
        files: ['scripts/visual/browser-snippets.js'],
        languageOptions: { ecmaVersion: 'latest', sourceType: 'commonjs', globals: globals.browser },
        rules: sharedRules,
    },
];
